### PR TITLE
Pike gating

### PR DESCRIPTION
**Pull request by xgerman**

### CODE REVIEW

**Comment by mattt416** [comment]
Seeing the following failure:

```13:36:47 /var/lib/jenkins/workspace/PR_rpc-octavia-pike-xenial-functional-test/rpc-octavia/gating/scripts/vars.sh: line 50: unexpected EOF while looking for matching `"'
[Pipeline] }
13:36:47 ERROR: script returned exit code 2```

**Review by mattt416 — DISMISSED** [review]
Missing closing double-quote.

**Comment by mattt416** [comment]
recheck_cit_xenial_functional_test

**Comment by mattt416** [comment]
recheck_cit_xenial_functional_test

**Comment by xgerman** [comment]
recheck_cit_xenial_functional_test

**Comment by xgerman** [comment]
recheck_cit_xenial_functional_test

**Pull request closed without merging**
