### PR TITLE
Pike gating

### PR DESCRIPTION
**Pull request by xgerman**

### CODE REVIEW

**Comment by xgerman** [comment]
recheck_cit_xenial_functional_test

**Comment by xgerman** [comment]
recheck_xenial_functional_test

**Comment by mattt416** [comment]
recheck_all

**Comment by mattt416** [comment]
recheck_all

**Comment by mattt416** [comment]
recheck_xenial_functional_test

**Comment by mattt416** [comment]
recheck_cit_xenial_functional_test

**Comment by mattt416** [comment]
recheck_all

**Pull request closed without merging**
