### PR TITLE
Bump RPC-O version to 14.1.10

### PR DESCRIPTION
**Pull request by xgerman**

### CODE REVIEW

**Comment by xgerman** [comment]
recheck_cit_xenial_functional_test

**Comment by xgerman** [comment]
recheck_cit_xenial_functional_test

**Comment by mattt416** [comment]
recheck_cit_xenial_functional_test

**Comment by xgerman** [comment]
recheck_cit_xenial_functional_test

**Review by FestivalBobcats — APPROVED** [review]

**Pull request merged**
